# Generated by Django 5.0 on 2024-01-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('category', models.CharField(default='Product category', max_length=70)),
                ('brand_name', models.CharField(default='Product brand', max_length=70)),
                ('name', models.CharField(default='Product title', max_length=70)),
                ('price', models.DecimalField(decimal_places=2, default='0,00', max_digits=10)),
                ('product_url', models.CharField(default='Default url', max_length=100)),
            ],
        ),
    ]
